spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 3000

    #lettuce 配置
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        ## 连接池中的最大空闲连接 默认 8
        max-idle: 8
        ## 连接池中的最小空闲连接 默认 0
        min-idle: 0

    #jedis 配置
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        ## 连接池中的最大空闲连接 默认 8
        max-idle: 8
        ## 连接池中的最小空闲连接 默认 0
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://127.0.0.1/temp